server:
  port: 0 # ?? ??? 0?? ???? ???? ??? ?????? ?. ??? ??? ?? ??? ?? ? ??? ??? ???.
spring:
  application:
    name: user-service
eureka:
  instance:
    # ??? 0?? ?? ??? ???? ??, Eureka ??????? IP:application name:port? ???? ??? ?? ? ???? ????? ? ?? ???? ?
    # ? ??? instance-id? ??? ??
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance.id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true  # Eureka ????? ?????? ??? ????? ?????.
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
